# Generated by Django 4.2.6 on 2023-11-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('csv_file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='TableDataFile',
        ),
    ]
