# Generated by Django 4.2.6 on 2024-02-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pjt_type',
            field=models.CharField(default='sample', max_length=20),
        ),
    ]
