# Generated by Django 4.2.6 on 2024-02-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_model', '0002_project_pjt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pjt_type',
            field=models.CharField(max_length=20),
        ),
    ]
